name: Deploy Hosting

on:
  workflow_dispatch:
  push:
    branches: [ main, wire-health-ci ]

concurrency:
  group: deploy-hosting-${{ github.ref }}
  cancel-in-progress: true

env:
  PROJECT_ID: razzlab

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            frontend/package-lock.json

      - name: Install and build frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Deploy hosting
        run: firebase deploy --only hosting --project $PROJECT_ID --force --token "${{ secrets.FIREBASE_TOKEN }}"
