name: Deploy Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: |
          echo "Starting deploy job..."

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Auth with service account
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > $HOME/gcp_sa.json
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/gcp_sa.json"

      - name: Install deps (root if present)
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          fi

      - name: Build frontend -> dist
        run: |
          cd frontend
          npm ci
          npm run build
          cd ..

      - name: Deploy Functions
        run: firebase deploy --only functions --project ${{ secrets.FIREBASE_PROJECT_ID }} --non-interactive

      - name: Deploy Hosting
        run: firebase deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT_ID }} --non-interactive

